version: 2

sources:
  - name: prod
    database: data-warehousing-402518
    schema: prod
    tables:
      - name: order_items
      - name: orders
      - name: retailers
      - name: shipping
      - name: shipping_items
      - name: materials
      