version: 2

sources:
  - name: prod
    database: data-warehousing-402518
    schema: source
    tables:
      - name: bill_of_materials
      - name: forecasts
      - name: order_items
      - name: orders
      - name: retailers
      - name: shipping
      - name: shipping_items
      